require_relative 'core_ext/kernel'
require_relative 'core_ext/pathname'
require_relative 'core_ext/string'
require_relative 'core_ext/array'
require_relative 'core_ext/argv'
require_relative 'core_ext/env'
